"""
TechPulse - Narration Stage
Converts each video's narration text into speech via Chatterbox-Turbo (open-source, expressive TTS),
slowed 8% for pacing (pitch preserved via ffmpeg), with word-level captions generated by transcribing
the final audio with faster-whisper - 85% of Shorts are watched muted, so burned-in captions are
treated as required output, not a nice-to-have.

Narration text may contain inline tags from the script stage:
  [SFX: description]                     - a sound effect cue at this point in the narration
  [VOICE:quote]quoted text[/VOICE]        - a segment to render in a second "quote" voice

This stage:
  1. Parses those tags out of the raw narration text.
  2. Synthesizes the quote segment(s) with a second reference voice (if one is
     configured) and the rest with the main voice, then concatenates them in order.
  3. Transcribes the final audio with word-level timestamps (faster-whisper) to
     build burned-in captions AND to resolve each [SFX:] tag to an actual timestamp
     in the finished audio (by matching the word position where the tag sat in the
     clean text against the transcribed words).
  4. Writes out "sfx_events": [{"description": ..., "timestamp": seconds}, ...] per
     video alongside the audio/captions paths, for the assembly stage to layer real
     sound effects in at the right moment. Assembly-side mixing is a separate stage,
     not implemented in this file.
"""

import json
import os
import re
import subprocess

import torchaudio
from chatterbox.tts import ChatterboxTTS
from faster_whisper import WhisperModel

AUDIO_DIR = "narration/audio"
WORDS_PER_CAPTION_CHUNK = 4  # short, punchy on-screen groups - easy to read at a glance on vertical video
SLOWDOWN_FACTOR = "0.92"  # 8% slower, pitch preserved

# Optional path to a reference audio clip for the "quote" voice. If this file
# doesn't exist, quote segments fall back to the main voice automatically -
# nothing breaks, it just won't sound distinct yet.
QUOTE_VOICE_REFERENCE = "narration/quote_voice_reference.wav"

SFX_TAG_RE = re.compile(r"\[SFX:\s*(.*?)\s*\]")
VOICE_TAG_RE = re.compile(r"\[VOICE:quote\](.*?)\[/VOICE\]", re.DOTALL)

_tts_model = None
_whisper_model = None


def get_tts_model():
    global _tts_model
    if _tts_model is None:
        _tts_model = ChatterboxTTS.from_pretrained(device="cpu")
    return _tts_model


def get_whisper_model():
    global _whisper_model
    if _whisper_model is None:
        _whisper_model = WhisperModel("base.en", device="cpu", compute_type="int8")
    return _whisper_model


def format_srt_timestamp(t):
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = int(t % 60)
    ms = int((t - int(t)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def parse_tags(raw_text):
    """
    Splits raw narration text into an ordered list of segments:
      {"type": "speech", "voice": "main"|"quote", "text": "..."}
      {"type": "sfx", "description": "...", "word_index_before": N}
    "word_index_before" is the count of speech words that come before this SFX
    tag in the CLEAN (tag-stripped) text - used later to line the tag up with a
    real timestamp from the transcription of the clean speech.
    Also returns clean_text: the narration with all tags stripped, ready for TTS.
    """
    segments = []
    clean_words_so_far = 0

    quote_spans = [(m.start(), m.end(), m.group(1)) for m in VOICE_TAG_RE.finditer(raw_text)]

    cursor = 0
    chunks = []  # (text, voice)
    for start, end, inner in quote_spans:
        if start > cursor:
            chunks.append((raw_text[cursor:start], "main"))
        chunks.append((inner, "quote"))
        cursor = end
    if cursor < len(raw_text):
        chunks.append((raw_text[cursor:], "main"))

    clean_parts = []
    for chunk_text, voice in chunks:
        last_end = 0
        for m in SFX_TAG_RE.finditer(chunk_text):
            before = chunk_text[last_end:m.start()]
            if before.strip():
                segments.append({"type": "speech", "voice": voice, "text": before})
                clean_parts.append(before)
                clean_words_so_far += len(before.split())
            segments.append({
                "type": "sfx",
                "description": m.group(1),
                "word_index_before": clean_words_so_far,
            })
            last_end = m.end()
        remainder = chunk_text[last_end:]
        if remainder.strip():
            segments.append({"type": "speech", "voice": voice, "text": remainder})
            clean_parts.append(remainder)
            clean_words_so_far += len(remainder.split())

    clean_text = "".join(clean_parts)
    clean_text = re.sub(r"\s+", " ", clean_text).strip()
    return segments, clean_text


def synthesize_speech_segments(segments, tts, has_quote_ref):
    audio_pieces = []
    for seg in segments:
        if seg["type"] != "speech":
            continue
        text = seg["text"].strip()
        if not text:
            continue
        if seg["voice"] == "quote" and has_quote_ref:
            wav = tts.generate(text, audio_prompt_path=QUOTE_VOICE_REFERENCE)
        else:
            wav = tts.generate(text)
        audio_pieces.append(wav)
    return audio_pieces


def generate_narration_audio_and_captions(raw_text, audio_out_path, srt_out_path):
    tts = get_tts_model()
    segments, clean_text = parse_tags(raw_text)
    has_quote_ref = os.path.exists(QUOTE_VOICE_REFERENCE)

    audio_pieces = synthesize_speech_segments(segments, tts, has_quote_ref)
    if not audio_pieces:
        raise RuntimeError("No speech segments produced from narration text.")

    combined = torch_cat_audio(audio_pieces)

    raw_path = audio_out_path.replace(".mp3", "_raw.wav").replace(".wav", "_raw.wav")
    torchaudio.save(raw_path, combined, tts.sr)

    subprocess.run(
        ["ffmpeg", "-y", "-i", raw_path, "-filter:a", f"atempo={SLOWDOWN_FACTOR}", audio_out_path],
        check=True, capture_output=True,
    )
    os.remove(raw_path)

    whisper = get_whisper_model()
    transcribed_segments, _ = whisper.transcribe(audio_out_path, word_timestamps=True)

    words = []
    for seg in transcribed_segments:
        for w in seg.words:
            words.append(w)

    if not words:
        return False, []

    srt_lines = []
    index = 1
    for i in range(0, len(words), WORDS_PER_CAPTION_CHUNK):
        group = words[i:i + WORDS_PER_CAPTION_CHUNK]
        start = group[0].start
        end = group[-1].end
        caption_text = " ".join(w.word.strip() for w in group)
        srt_lines.append(str(index))
        srt_lines.append(f"{format_srt_timestamp(start)} --> {format_srt_timestamp(end)}")
        srt_lines.append(caption_text)
        srt_lines.append("")
        index += 1

    with open(srt_out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(srt_lines))

    sfx_events = []
    for seg in segments:
        if seg["type"] != "sfx":
            continue
        idx = min(seg["word_index_before"], len(words) - 1) if words else 0
        if idx < 0:
            idx = 0
        timestamp = words[idx].start if idx < len(words) else words[-1].end
        sfx_events.append({"description": seg["description"], "timestamp": round(timestamp, 2)})

    return True, sfx_events


def torch_cat_audio(pieces):
    import torch
    return torch.cat(pieces, dim=-1)


def generate_all_narrations(videos_path="video/latest_videos.json", out_path="narration/latest_narrations.json"):
    os.makedirs(AUDIO_DIR, exist_ok=True)
    with open(videos_path) as f:
        videos = json.load(f)

    results = []
    for i, v in enumerate(videos):
        audio_path = f"{AUDIO_DIR}/narration_{i}.wav"
        srt_path = f"{AUDIO_DIR}/narration_{i}.srt"
        try:
            has_captions, sfx_events = generate_narration_audio_and_captions(
                v["narration"], audio_path, srt_path
            )
            item = {**v, "audio_path": audio_path, "sfx_events": sfx_events}
            if has_captions:
                item["captions_path"] = srt_path
            else:
                print(f"  No words transcribed for '{v['title']}' - proceeding without captions.")
            results.append(item)
            print(f"Narrated: {v['title']} ({len(sfx_events)} SFX cue(s))")
        except Exception as e:
            print(f"Error narrating {v['title']}: {e}")

    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Saved {len(results)} narrations to {out_path}")


if __name__ == "__main__":
    generate_all_narrations()
