"""
TechPulse - Narration Stage
Converts each video's narration text into speech via Chatterbox-Turbo (open-source, expressive TTS),
slowed 8% for pacing (pitch preserved via ffmpeg), with word-level captions generated by transcribing
the final audio with faster-whisper - 85% of Shorts are watched muted, so burned-in captions are
treated as required output, not a nice-to-have.
"""

import json
import os
import subprocess

import torchaudio
from chatterbox.tts import ChatterboxTTS
from faster_whisper import WhisperModel

AUDIO_DIR = "narration/audio"
WORDS_PER_CAPTION_CHUNK = 4  # short, punchy on-screen groups - easy to read at a glance on vertical video
SLOWDOWN_FACTOR = "0.92"  # 8% slower, pitch preserved

_tts_model = None
_whisper_model = None


def get_tts_model():
    global _tts_model
    if _tts_model is None:
        _tts_model = ChatterboxTTS.from_pretrained(device="cpu")
    return _tts_model


def get_whisper_model():
    global _whisper_model
    if _whisper_model is None:
        _whisper_model = WhisperModel("base.en", device="cpu", compute_type="int8")
    return _whisper_model


def format_srt_timestamp(t):
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = int(t % 60)
    ms = int((t - int(t)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def generate_narration_audio_and_captions(text, audio_out_path, srt_out_path):
    tts = get_tts_model()
    wav = tts.generate(text)

    raw_path = audio_out_path.replace(".mp3", "_raw.wav").replace(".wav", "_raw.wav")
    torchaudio.save(raw_path, wav, tts.sr)

    subprocess.run(
        ["ffmpeg", "-y", "-i", raw_path, "-filter:a", f"atempo={SLOWDOWN_FACTOR}", audio_out_path],
        check=True, capture_output=True,
    )
    os.remove(raw_path)

    whisper = get_whisper_model()
    segments, _ = whisper.transcribe(audio_out_path, word_timestamps=True)

    words = []
    for seg in segments:
        for w in seg.words:
            words.append(w)

    if not words:
        return False

    srt_lines = []
    index = 1
    for i in range(0, len(words), WORDS_PER_CAPTION_CHUNK):
        group = words[i:i + WORDS_PER_CAPTION_CHUNK]
        start = group[0].start
        end = group[-1].end
        caption_text = " ".join(w.word.strip() for w in group)
        srt_lines.append(str(index))
        srt_lines.append(f"{format_srt_timestamp(start)} --> {format_srt_timestamp(end)}")
        srt_lines.append(caption_text)
        srt_lines.append("")
        index += 1

    with open(srt_out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(srt_lines))
    return True


def generate_all_narrations(videos_path="video/latest_videos.json", out_path="narration/latest_narrations.json"):
    os.makedirs(AUDIO_DIR, exist_ok=True)
    with open(videos_path) as f:
        videos = json.load(f)

    results = []
    for i, v in enumerate(videos):
        audio_path = f"{AUDIO_DIR}/narration_{i}.wav"
        srt_path = f"{AUDIO_DIR}/narration_{i}.srt"
        try:
            has_captions = generate_narration_audio_and_captions(v["narration"], audio_path, srt_path)
            item = {**v, "audio_path": audio_path}
            if has_captions:
                item["captions_path"] = srt_path
            else:
                print(f"  No words transcribed for '{v['title']}' - proceeding without captions.")
            results.append(item)
            print(f"Narrated: {v['title']}")
        except Exception as e:
            print(f"Error narrating {v['title']}: {e}")

    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Saved {len(results)} narrations to {out_path}")


if __name__ == "__main__":
    generate_all_narrations()
